# Generated by Django 3.1.7 on 2021-04-26 14:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('voter_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=300)),
                ('gender', models.CharField(max_length=45)),
                ('age', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=45)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'voter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('elction_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('reg_start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('reg_end_date', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('Candidate_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('AADHAR_NO', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('transgender', 'transgender')], max_length=20)),
                ('age', models.CharField(max_length=45)),
                ('vote_count', models.IntegerField(default=0)),
                ('Candidate_photo', models.ImageField(upload_to='')),
                ('party_symbol', models.ImageField(null=True, upload_to='')),
                ('election', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='e_vote.election')),
            ],
        ),
    ]
